#!/usr/bin/env python3
"""Verify the integrity and basic hygiene of the public release archive."""

from __future__ import annotations

import csv
import hashlib
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "checksums" / "SHA256SUMS.tsv"
UNWANTED_NAMES = {".DS_Store", "__pycache__"}
UNWANTED_SUFFIXES = {".pyc", ".pyo", ".swp", ".tmp", ".bak"}
TEXT_SUFFIXES = {".md", ".txt", ".tsv", ".csv", ".py", ".r", ".yml", ".yaml", ".json"}
FORBIDDEN_PATTERNS = {
    "personal absolute path": re.compile(r"/Users/|[A-Za-z]:\\\\Users\\\\"),
    "local username": re.compile(r"linhangfeng", re.IGNORECASE),
    "assistant attribution": re.compile(r"ChatGPT|OpenAI|Codex|Claude|generated by AI|as an AI", re.IGNORECASE),
    "unresolved placeholder": re.compile(r"AUTHOR INFORMATION TO BE INSERTED|PERMANENT REPOSITORY URL|\bTODO\b|\bFIXME\b"),
    "credential-like token": re.compile(r"ghp_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,}|AKIA[0-9A-Z]{16}"),
}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def main() -> None:
    with MANIFEST.open(encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle, delimiter="\t"))

    failures: list[str] = []
    expected = {row["file"] for row in rows}
    for row in rows:
        path = ROOT / row["file"]
        if not path.is_file():
            failures.append(f"missing: {row['file']}")
            continue
        if str(path.stat().st_size) != row["size_bytes"]:
            failures.append(f"size mismatch: {row['file']}")
        if sha256(path) != row["sha256"]:
            failures.append(f"checksum mismatch: {row['file']}")

    junk = [
        str(path.relative_to(ROOT))
        for path in ROOT.rglob("*")
        if path.name in UNWANTED_NAMES or path.suffix.lower() in UNWANTED_SUFFIXES
    ]
    failures.extend(f"unwanted file: {item}" for item in junk)

    actual = {
        str(path.relative_to(ROOT))
        for path in ROOT.rglob("*")
        if path.is_file()
        and ".git" not in path.parts
        and "outputs" not in path.relative_to(ROOT).parts
        and path != MANIFEST
    }
    failures.extend(f"unlisted release file: {item}" for item in sorted(actual - expected))
    failures.extend(f"manifest entry has no release file: {item}" for item in sorted(expected - actual))

    for relative in sorted(actual):
        path = ROOT / relative
        if path.resolve() == Path(__file__).resolve():
            continue
        if path.suffix.lower() not in TEXT_SUFFIXES:
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        for label, pattern in FORBIDDEN_PATTERNS.items():
            if pattern.search(text):
                failures.append(f"{label}: {relative}")

    if failures:
        for item in failures:
            print(item)
        raise SystemExit("RELEASE_INTEGRITY=FAIL")

    print(f"FILES_VERIFIED={len(rows)}")
    print("UNWANTED_FILE_COUNT=0")
    print("UNLISTED_FILE_COUNT=0")
    print("HYGIENE_SCAN=PASS")
    print("RELEASE_INTEGRITY=PASS")


if __name__ == "__main__":
    main()
